services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # host:container
    volumes:
      - ./backend:/app           # mount local code
      - /app/node_modules        # container-only node_modules
    environment:
      - PORT=5000
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"              # host:container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    command: npm run dev
